# community
community:
  path:
    domain: http://localhost:8080
# spring
spring:
  # Thymeleaf
  thymeleaf:
    # 设置为 false，修改 thymeleaf 的 template 可以不用重启 springboot
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  # DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ubuntu.wsl:3306/community?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: JX34&
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  # Mail
  mail:
    host: smtp.163.com
    port: 465
    username: JunXiao_Song@163.com
    password: QXBYWOPDTTDHALCI
    protocol: smtps
# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.aidan.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
# server Properties
server:
  servlet:
    context-path: /community